FROM redhat/ubi9

# 1. Instalar systemd, openssh-server, sudo y herramientas del sistema necesarias
RUN dnf clean all && \
    dnf makecache && \
    dnf install -y systemd systemd-udev procps-ng && \
    dnf clean all

# 2. Definir systemd como el proceso principal (PID 1)
CMD ["/usr/sbin/init"]
