FROM ubuntu:latest

ENV DEBIAN_FRONTEND=noninteractive

# 1. Instalar systemd, openssh-server, sudo y limpiar
RUN apt-get update && apt-get install -y \
    systemd \
    systemd-sysv && \
    apt-get clean && rm -rf /var/lib/apt/lists/*

# 2. Definir systemd como el proceso principal
#VOLUME [ "/sys/fs/cgroup", "/run", "/tmp" ]
CMD ["/lib/systemd/systemd"]
