ervices:
  ansible-control:
    build:
      context: .
      dockerfile: Dockerfile.control
    container_name: ansible-control
    tty: true
    volumes:
      - ./ansible_data:/home/ansible
    networks:
      - ansible-net

  ubuntu-node1:
    build:
      context: .
      dockerfile: Dockerfile.ubuntu
    container_name: ubuntu-node1
    privileged: true
    command: /lib/systemd/systemd
    tty: true
    tmpfs:
      - /run
      - /run/lock
      - /tmp
    networks:
      - ansible-net

  rhel-node1:
    build:
      context: .
      dockerfile: Dockerfile.rhel
    container_name: rhel-node1
    privileged: true
    command: /sbin/init
    tty: true
    tmpfs:
      - /run
      - /run/lock
      - /tmp
    networks:
      - ansible-net

networks:
  ansible-net:
    driver: bridge
