services:
  ansible-control:
    build:
      context: .
      dockerfile: Dockerfile.control
    container_name: ansible-control
    tty: true
    volumes:
      - ./ansible_data:/home/ansible
    networks:
      - ansible-net

  ubuntu-node1:
    build:
      context: .
      dockerfile: Dockerfile.ubuntu
    container_name: ubuntu-node1
    tty: true
    networks:
      - ansible-net

  ubuntu-node2:
    build:
      context: .
      dockerfile: Dockerfile.ubuntu
    container_name: ubuntu-node2
    tty: true
    networks:
      - ansible-net

  rhel-node1:
    build:
      context: .
      dockerfile: Dockerfile.rhel
    container_name: rhel-node1
    tty: true
    networks:
      - ansible-net

  rhel-node2:
    build:
      context: .
      dockerfile: Dockerfile.rhel
    container_name: rhel-node2
    tty: true
    networks:
      - ansible-net

networks:
  ansible-net:
    driver: bridge
