FROM rockylinux:9

# 1. Limpiar caché, actualizar y luego instalar paquetes necesarios
RUN dnf clean all && \
    dnf makecache && \
    dnf install -y openssh-server sudo && \
    dnf clean all

# 2. Crear el usuario ansible, definir su contraseña y agregarlo al grupo wheel (sudo en Red Hat)
RUN useradd -m -s /bin/bash ansible && \
    echo "ansible:password" | chpasswd && \
    usermod -aG wheel ansible

# 3. CREAR Y ASEGURAR LA CARPETA .ssh (Aquí está la clave del error anterior)
RUN mkdir -p /home/ansible/.ssh && \
    chmod 700 /home/ansible/.ssh && \
    chown -R ansible:ansible /home/ansible

# 4. Generar las llaves del host y configurar SSH
RUN ssh-keygen -A && \
    sed -i 's/#PasswordAuthentication yes/PasswordAuthentication yes/' /etc/ssh/sshd_config

EXPOSE 22

# 5. Iniciar el servicio SSH en primer plano
CMD ["/usr/sbin/sshd", "-D"]
