[web]
ubuntu-node1 ansible_python_interpreter=/usr/bin/python3.14
rhle-node1 ansible_python_interpreter=/usr/bin/python3.9

[db]
ubuntu-node2 
#ansible_python_interpreter=/usr/bin/python3.14
rhle-node2 
#ansible_python_interpreter=/usr/bin/python3.9

#[all:vars]
#ansible_user=ansible
#ansible_become_password=password
