FROM ubuntu:latest

ENV DEBIAN_FRONTEND=noninteractive

# 1. Instalar systemd, openssh-server, sudo y limpiar
RUN apt-get update && apt-get install -y \
    systemd \
    systemd-sysv \
    openssh-server \
    sudo && \
    apt-get clean && rm -rf /var/lib/apt/lists/*

# 2. Crear el usuario ansible y darle permisos de sudo
RUN useradd -m -s /bin/bash ansible && \
    echo "ansible:password" | chpasswd && \
    usermod -aG sudo ansible

RUN echo "ansible ALL=(ALL) NOPASSWD:ALL" >> /etc/sudoers.d/ansible

# 3. Preparar la carpeta .ssh
RUN mkdir -p /home/ansible/.ssh && \
    chmod 700 /home/ansible/.ssh

# 4. Inyectar la llave pública directamente (Asegúrate de tener id_rsa.pub junto a este Dockerfile)
COPY id_rsa.pub /home/ansible/.ssh/authorized_keys

# 5. Ajustar permisos estrictos requeridos por SSH y propietario de la carpeta
RUN chmod 600 /home/ansible/.ssh/authorized_keys && \
    chown -R ansible:ansible /home/ansible

# 6. Configurar SSH
RUN ssh-keygen -A && \
    sed -i 's/#PasswordAuthentication yes/PasswordAuthentication yes/' /etc/ssh/sshd_config

# 7. Habilitar SSH mediante Systemd
RUN systemctl enable ssh

EXPOSE 22

# 8. Definir systemd como el proceso principal
CMD ["/lib/systemd/systemd"]
